spring:
  security:
    user:
      password: root123
  config:
    use-legacy-processing: false
  datasource:
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 20000
    #    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.chy440m86mlz.us-east-1.rds.amazonaws.com:5432/parking_lot_db
    database: parking_lot_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

login:
  username: admin@h12.com
  password: root123