
server:
  scheme: http
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: mappings
#        include: *
#        include: info, health, configprops, env, prometheus, metrics, openapi, swagger-ui
  security:
    enabled: false

springdoc:
  use-management-port: false
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

spring:
  security:
    user:
      password: root123
  config:
    use-legacy-processing: false
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/parking_lot_db
    database: parking_lot_db
    username: postgres
    generateDDL: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
#          auto: validate
          auto: update
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ""


