
server:
  scheme: http
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: info, health, configprops, env, prometheus, metrics
#  security:
#    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

springdoc:
  use-management-port: true
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  config:
    use-legacy-processing: false
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/parking_lot_db
    database: parking_lot_db
    username: postgres
    generateDDL: true
  jpa:
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

